---
title: "Méthodes d'Analyse factorielle"
author: "MP Etienne"
format: html
toc: true
date: last-modified
date-format: "[Dernière Mise à jour] Octobre 2024"
css: mpe_pres_revealjs.css
execute: 
  freeze: auto
---


# Description du cours

Ce cours présente des techniques statistiques pour décire et viusualiser des données multivariés. Il présentera à la fois les fondements mathématiques (géométriques) mais fera surtout la part belle à la mise en oeuvre pratioque de ces outils. A l'issue de ce cours, vous disposerez d'un ensemble de méthodes pour analyser des ensembles de données complexes et créer des représentations visuelles qui révèlent des motifs, des tendances et des relations entre plusieurs variables. Le cours couvre les sujets suivants :


# Contenu

-   **Analyse en Composantes Principales (ACP)** : Un outil puissant de réduction dimensionnelle qui simplifie les grands ensembles de données tout en préservant autant que possible la variation. Les étudiants apprendront à visualiser des données à haute dimension à l'aide de l'ACP, rendant ainsi plus faciles à interpréter les relations complexes. Un extension, l'Analyse Factorielle Multiple (AFM) permet de prendre en compte des variables quantitatives organisées par groupe (on veut distinguer les variables physiques, des variables chimiques par exemple).

-   **Analyse Factorielle Discriminante (AFD)** : Cette technique aide à classifier les observations dans des groupes prédéfinis. Le cours se concentrera sur la manière de différencier visuellement les groupes en utilisant plusieurs variables prédictives et d'interpréter les résultats.

-   **Analyse de Corrélation Multiple (ACM)** : Les étudiants exploreront comment évaluer et visualiser les relations entre plusieurs variables quantitatives simultanément, à l'aide de représentations graphiques qui rendent les structures de corrélation claires et instructives.

-   **Analyse des Correspondances Multiples (ACM)** : En étendant l'analyse des correspondances aux données catégorielles, cette technique permet aux étudiants de visualiser des motifs dans de grands ensembles de données catégorielles, en mettant en évidence des structures sous-jacentes dans un format visuellement interprétable.

Le cours mettra un accent particulier sur la visualisation des ensembles de données multivariés complexes. Les concepts théoriques seront complétés par des exercices pratiques, où les étudiants utiliseront des logiciels statistiques (R, Python, etc.) pour générer des visualisations informatives telles que des biplots, des nuages de points et des matrices de corrélation. Ces outils visuels sont précieux pour communiquer les résultats des analyses multivariées de manière intuitive et accessible.

À la fin du cours, les étudiants seront compétents dans l'application des méthodes multivariées à une variété d'ensembles de données et auront les compétences nécessaires pour créer des visualisations qui transmettent efficacement les insights découverts grâce à l'analyse statistique.



# Organisation du cours

* 12h de cours 
* 12h de De TD/TP

Chaque cours contiendra un exemple détaillé et la mise en oeuvre pratique de la méthode étudiée ainsi que la présentation des concepts mathématiques (essentiellement géométriques) sur lesquels elle repose.

# Prérequis 

 Une connaissance de base des statistiques, de l'algèb.re linéaire et une maîtrise des logiciels statistiques (R ou Python) sont recommandées